set rtp +=~/.vim

" Install vim-plug if we don't already have it
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins
call plug#begin('~/.vim/plugged')

Plug 'christoomey/vim-tmux-navigator'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'flazz/vim-colorschemes'
Plug 'sheerun/vim-polyglot'                           " thrift colorescheme
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-fugitive'
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
Plug 'MarcWeber/vim-addon-manager-known-repositories' " random shit
Plug 'scrooloose/nerdtree'
Plug 'jlanzarotta/bufexplorer'                        " Bufexplorer
Plug 'itchyny/lightline.vim'                          " status line
Plug 'derekwyatt/vim-scala'
Plug 'airblade/vim-gitgutter'
Plug 'kien/rainbow_parentheses.vim'
Plug 'haya14busa/incsearch.vim'
Plug 'rust-lang/rust.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dense-analysis/ale'
Plug 'davidhalter/jedi-vim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }
Plug 'nanotee/zoxide.vim'
Plug 'puremourning/vimspector'
Plug 'ruanyl/vim-gh-line'                             " Open git commit line highlight URL link from line in file
Plug 'tpope/vim-abolish'                              " change snake-case to camel_case with 'cr-'
Plug 'kien/ctrlp.vim'                                 " fuzzy-finder

call plug#end()
autocmd FileType json syntax match Comment +\/\/.\+$+

filetype plugin indent on

" My Configs
set cursorline
source ~/.vim/plugin_configs.vim " mappings/settings specific to the above plugins
source ~/.vim/work_configs.vim
